# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 383cef930a86b9ba436a16049162ea8eb9c5791a4afe86a327e23cf966c31b56b6b63cb8ecc8e7da934c998087c56e1c7d56c84ffc57f1236a3361c3ab381b68

test:
  secret_key_base: be60ce392104c1bc6b357d606c8209278d92d1733a23c6d9632cbe4ce4c5fea0edd957f78067e9ce6d9d058b715d55a2cec8c431d870bc89f85dcd83c69e34d9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
